version: "3.3"
services:
  web:
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/home/flask/app/
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
  redis:
    restart: always
    image: "redis:alpine"
    expose:
      - "6379"
  postgres:
    restart: always
    image: postgres:alpine
  # Mount an initialization script and the persistent postgresql data volume
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - slurm_data:/var/lib/postgresql/data

  # Pass postgres environment variables
    environment:
      POSTGRES_PASSWORD: s1urmpa55
      POSTGRES_DB: slurm_app

  # Expose port 5432 to other docker containers
    expose:
      - "5432"
volumes:
  slurm_data:
