version: "3.9"
services:
  app:
    image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}.${CI_PIPELINE_ID}
    build: .
    ports:
      - "80:80"
    environment:
      DB_HOST: xpaste-postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: xpaste
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
      SECRET_KEY_BASE: xxxxxxxxxxxxxxxxxxxxxxxxx
  redis:
    restart: always
    image: "redis:alpine"
networks:
  default:
    external: true
    name: xpaste-net
