FROM golang:1.17.0

WORKDIR $GOPATH/src/slurm.io/main

COPY . .
RUN go mod download
RUN go mod verify

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/main

COPY ./static /static

EXPOSE 9001

ENTRYPOINT ["/go/bin/main"]
